# Generated by Django 5.2.4 on 2025-07-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20250702_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=40),
        ),
    ]
